### ISSUE TITLE
Review Vignette Content

### ISSUE THREAD

**Issue by bryanhanson** [r-hyperspec/hySpc.read.jdx#13]
Bryan will review the language and contents (a working vignette frame work should be ready shortly).

**Comment by bryanhanson** [comment]
The vignette is basically done (and there is not much to it).  However, the vignette is not being rendered quite correctly.  The cross references are not being formatted correctly and the figure referencing is not working.  Take a [look](https://r-hyperspec.github.io/hySpc.read.jdx/articles/hySpc-read-jdx.html).

I've tried all sorts of things but need someone with fresh eyes to take a look. @sangttruong could you take a look please?  It will be a good chance for you to see exactly how these vignettes are built and since some of this process is new to you, you might catch my error.  You can compare to `cbeleites/hyperSpec/vignettes/hyperSpec.Rmd` for example.  Thanks.

Use branch `issue/#13` but you'll have to merge into `develop` and push that to do a final verification.

**Comment by cbeleites** [comment]
We decided in the meeting today to delete the vignette, since it only shows one import example which is also available as example in the man page.
