### ISSUE TITLE
unit testing

### ISSUE THREAD

**Issue by cbeleites** [r-hyperspec/hySpc.read.jdx#16]
As it is, we have a test coverage of only 50 %.

Is there a suitable file to test with a spectrum with real and imaginary part? If so,

- [x] add test file
- [x] write unit test

**Comment by bryanhanson** [comment]
Closed via https://github.com/r-hyperspec/hySpc.read.jdx/commit/3ffd511f20660397e057f7006f1029baedb5e07c
