### ISSUE TITLE
Improve code coverage

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hySpc.read.jdx#20]
[![Codecov](https://codecov.io/gh/r-hyperspec/hySpc.read.jdx/branch/develop/graph/badge.svg)](https://codecov.io/gh/r-hyperspec/hySpc.read.jdx?branch=develop)

@bryanhanson, is it possible/reasomable to improve code coverage to reach more than 71%?

**Comment by bryanhanson** [comment]
Not sure how `codecov` works in this situation.  The function has two cases, each of which are tested.  I guess the coverage might go up if I test the stop condition? What do you think?  Is there something else to be tested?

**Comment by GegznaV** [comment]
>  I guess the coverage might go up if I test the stop condition? 

Yes, I think, that the `stop()` condition should be tested if possible.

**Comment by bryanhanson** [comment]
Now 100% via https://github.com/r-hyperspec/hySpc.read.jdx/commit/8463a7620cc656bf479f1e489f0bad7fe7064b30

**Comment by GegznaV** [comment]
Great 👍
