### ISSUE TITLE
Suppress/capture unit test output  to console

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hySpc.read.jdx#21]
Unit tests produce this output:

![image](https://user-images.githubusercontent.com/12725868/127315458-52454506-8cb7-45a1-a98a-622d9848d76c.png)

Is it expected?

Can we suppress or capture unit test output to have a more clean `testthat` output? Additional unit tests/checks can solve this.

**Comment by bryanhanson** [comment]
This is the expected output, as the input file is this case is corrupt and `readJDX::readJDX` issues this report.  I build and check via a `make` file and I don't see this level of detail. It must be a `RStudio` feature to show the output of a successful test.

**Comment by GegznaV** [comment]
> It must be an RStudio feature to show the output of a successful test.

Actually, the output was present on GHA too. E.g.. [here](https://github.com/r-hyperspec/hySpc.read.jdx/runs/3233726280?check_suite_focus=true) on `ubuntu-18.04 (R-release) `:

![image](https://user-images.githubusercontent.com/12725868/128065881-b890ee3b-81de-4784-941d-2326c241f7a9.png)
