### ISSUE TITLE
Add wavelength units to the object

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hySpc.read.jdx#22]
Wouldn't it be reasonable to add `##XUNITS=` as the label of wavelengths?

```r
file <- system.file("extdata", "SBO.jdx", package = "readJDX")
list_jdx <- readJDX(file)
list_jdx
```
![image](https://user-images.githubusercontent.com/12725868/127670552-7bdddc2c-8c5e-4645-bab9-e06bda78cf92.png)

e.g.:
```r
meta <- list_jdx$metadata
sub("^.*=", "", meta[grepl("XUNITS", meta)])
## [1] "1/CM"
```

What do you think, @bryanhanson?

**Comment by bryanhanson** [comment]
Reasonable, `XUNITS` is a required field in the JCAMP standard. Would you also like `YUNITS`?

**Comment by GegznaV** [comment]
Yes, if `YUNITS` is present, it should also be added as a label.
