### ISSUE TITLE
unnecessary duplicate code

### ISSUE THREAD

**Issue by cbeleites** [r-hyperspec/hySpc.read.jdx#27]
There's twice the code block:

```r
    spc@data$filename <- file
    spc@label$filename <- file
    return(list(metadata = list_jdx[[2]], hyperSpec = spc))
```
in read.jdx.R, and this is not necessary.

Please rewrite @sangttruong 

see also: #24 and #26

**Comment by GegznaV** [comment]
At first, #25 should be merged to avoid Git conflicts.

- #25

**Comment by GegznaV** [comment]
> There's twice the code block

Yes, it is a good practice to write DRY code. (DRY = Do not Repeat Yourself). So thanks, @cbeleites, for spotting this.

**Comment by GegznaV** [comment]
See also:
- #23
- #24 
- #26
