### ISSUE TITLE
Argument name: `debug` or `debuglevel`?

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hySpc.read.jdx#34]
In other packages of `hyperSpec` family, the parameter is called `debuglevel` and not `debug` (e.g., in **`hyperSpec`**'s hyperSpec::spc_fit_poly_below()`). So should the parameter name be consistent with `hyperSpec` or `readJDX` package?

**Comment by bryanhanson** [comment]
I'd say it should be consistent with the `hyperSpec` world for the best user experience.
